# Pandas Handson

https://www.kaggle.com/datasets/rohitsahoo/sales-forecasting/download/1vOThCy3PPVh4AoJQ22i%2Fversions%2Flvlh3t9jyYd6ugFM2Vhn%2Ffiles%2Ftrain.csv?datasetVersionNumber=2

https://www.kaggle.com/datasets/rohitsahoo/sales-forecasting?resource=download

In [2]:
import pandas as pd
import numpy as np

In [3]:
realDF = pd.read_csv("Dataset/train.csv")
df = realDF.copy()

In [4]:
print(df.head())
print(df.shape)

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales
0                  Bush Somerset Collection Bookcase  261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2  Self-Adhesive Address Labels for Typewriters b...   14.6200
3      Bretford CR4500 Series Slim Rectangular Table  957.5775
4                     Eldon Fold 'N Roll Cart System   22.3680
(9800, 18)

---

1) Print the top 5 and last 7 rows.
2) Print the number of rows and columns
3) Print the data types of every col
4) Print the names of every col

In [5]:
# 1) Top 5 and Last 7 rows
print("TOP 5 ROWS:")
print(df.head(5))

print("\nLAST 7 ROWS:")
print(df.tail(7))

TOP 5 ROWS:
   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales
0                  Bush Somerset Collection Bookcase  261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2  Self-Adhesive Address Labels for Typewriters b...   14.6200
3      Bretford CR4500 Series Slim Rectangular Table  957.5775
4                     Eldon Fold 'N Roll Cart System   22.3680

LAST 7 ROWS:
      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
9793    9794  CA-2015-127166  21/05/2015  23/05/2015    Second Class
9794    9795  CA-2015-127166  21/05/2015  23/05/2015    Second Class
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country     City  \
9793    KH-16360  Katherine Hughes   Consumer  United States  Houston
9794    KH-16360  Katherine Hughes   Consumer  United States  Houston
9795    SH-19975     Sally Hughsby  Corporate  United States  Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States   Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States   Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States   Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States   Toledo

         State  Postal Code   Region       Product ID         Category  \
9793     Texas      77070.0  Central  OFF-PA-10001560  Office Supplies
9794     Texas      77070.0  Central  OFF-BI-10000977  Office Supplies
9795  Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies
9796      Ohio      43615.0     East  OFF-AR-10001374  Office Supplies
9797      Ohio      43615.0     East  TEC-PH-10004977       Technology
9798      Ohio      43615.0     East  TEC-PH-10000912       Technology
9799      Ohio      43615.0     East  TEC-AC-10000487       Technology

     Sub-Category                                       Product Name    Sales
9793        Paper        Adams Telephone Message Books, 5 1/4” x 11”    4.832
9794      Binders                 Ibico Plastic Spiral Binding Combs   18.240
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.798
9796          Art           BIC Brite Liner Highlighters, Chisel Tip   10.368
9797       Phones                                        GE 30524EE4  235.188
9798       Phones           Anker 24W Portable Micro USB Car Charger   26.376
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive   10.384

In [6]:
# 2) Number of rows and columns
print("\nNUMBER OF ROWS AND COLUMNS:")
rows, cols = df.shape
print(f"Rows   : {rows}")
print(f"Columns: {cols}")
print(f"Shape  : {df.shape}")

NUMBER OF ROWS AND COLUMNS:
Rows   : 9800
Columns: 18
Shape  : (9800, 18)

In [7]:
# 3) Data types of every column
print("\nDATA TYPES OF EVERY COLUMN:")
print(df.dtypes)

DATA TYPES OF EVERY COLUMN:
Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code      float64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
dtype: object

In [8]:
# 4) Names of every column
print("\nCOLUMN NAMES:")
print(df.columns.tolist())

COLUMN NAMES:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales']

---

5) Find if there are any null values.
6) Drop the null values
7) Create a function which takes the data frame( as a parameter) and the function should fill the null values in the string/object data type column with mode of the column and the numerical col null values with the mean.

In [9]:
# 5) Find if there are any null values
print("NULL VALUES PER COLUMN:")
print(df.isnull().sum())

print("\nANY NULL VALUES IN DATAFRAME:", df.isnull().values.any())
print("TOTAL NULL VALUES:", df.isnull().sum().sum())

NULL VALUES PER COLUMN:
Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

ANY NULL VALUES IN DATAFRAME: True
TOTAL NULL VALUES: 11

In [10]:
# 6) Drop null values
df_dropped = df.dropna()
print("\nShape BEFORE dropping nulls:", df.shape)
print("Shape AFTER  dropping nulls:", df_dropped.shape)

Shape BEFORE dropping nulls: (9800, 18)
Shape AFTER  dropping nulls: (9789, 18)

In [11]:
# 7) Function to fill nulls — mode for object cols, mean for numeric cols
def fill_null_values(df):
    df = df.copy()  # avoid modifying the original
    for col in df.columns:
        if df[col].isnull().sum() > 0:                  # only process cols with nulls
            if df[col].dtype == 'object':
                df[col] = df[col].fillna(df[col].mode()[0])   # mode for string cols
            else:
                df[col] = df[col].fillna(df[col].mean())      # mean for numeric cols
    return df

df_filled = fill_null_values(df)

print("\nNull values BEFORE filling:")
print(df.isnull().sum()[df.isnull().sum() > 0])

print("\nNull values AFTER filling:")
print(df_filled.isnull().sum().sum(), "← should be 0")

Null values BEFORE filling:
Postal Code    11
dtype: int64

Null values AFTER filling:
0 ← should be 0

---

8) Convert Order Date and Ship Date to datetime

In [12]:
# Convert Order Date and Ship Date from string to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date']  = pd.to_datetime(df['Ship Date'],  dayfirst=True)

In [13]:
print(df.dtypes)

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code             float64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
dtype: object

In [14]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [15]:
realDF

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [16]:
newDF = realDF.copy()
newDF['Order Date'] = pd.to_datetime(newDF['Order Date'], format='mixed')
newDF['Ship Date']  = pd.to_datetime(newDF['Ship Date'], format='mixed')

In [17]:
newDF

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,2017-12-06,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,2016-11-10,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,2016-11-10,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,2016-12-01,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,2016-12-01,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,2016-12-01,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,2016-12-01,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

---

9) Create Order Year and Ship Year column
10) Remove the Row Id col

In [18]:
# 9) Create Order Year and Ship Year columns
newDF['Order Year'] = newDF['Order Date'].dt.year
newDF['Ship Year']  = newDF['Ship Date'].dt.year

print(newDF[['Order Date', 'Order Year', 'Ship Date', 'Ship Year']].head())

  Order Date  Order Year  Ship Date  Ship Year
0 2017-08-11        2017 2017-11-11       2017
1 2017-08-11        2017 2017-11-11       2017
2 2017-12-06        2017 2017-06-16       2017
3 2016-11-10        2016 2016-10-18       2016
4 2016-11-10        2016 2016-10-18       2016

In [19]:
# 10) Remove the Row ID column
newDF.drop(columns=['Row ID'])

print(newDF.shape)
print(newDF.columns.tolist())

(9800, 20)
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Order Year', 'Ship Year']

---

11) Find the avg, min, maxc Sales.
12) Find the total number of unqiue customers
13) Find the unique Countries, Sates.

In [20]:
df = realDF.copy()

In [21]:
# 11) Avg, Min, Max Sales
print("SALES STATISTICS:")
print(f"Average Sales : {df['Sales'].mean():.2f}")
print(f"Minimum Sales : {df['Sales'].min():.2f}")
print(f"Maximum Sales : {df['Sales'].max():.2f}")

SALES STATISTICS:
Average Sales : 230.77
Minimum Sales : 0.44
Maximum Sales : 22638.48

In [22]:
df['Sales'].mean()

np.float64(230.76905945918367)

In [23]:
# 12) Total number of unique customers
print("\nUNIQUE CUSTOMERS:")
print(df['Customer ID'].nunique())

UNIQUE CUSTOMERS:
793

In [24]:
# 13) Unique Countries and States
print("\nUNIQUE COUNTRIES:")
print(df['Country'].unique())

print("\nUNIQUE STATES:")
print(df['State'].unique())

print(f"\nTotal Unique Countries : {df['Country'].nunique()}")
print(f"Total Unique States    : {df['State'].nunique()}")

UNIQUE COUNTRIES:
<StringArray>
['United States']
Length: 1, dtype: str

UNIQUE STATES:
<StringArray>
[            'Kentucky',           'California',              'Florida',
       'North Carolina',           'Washington',                'Texas',
            'Wisconsin',                 'Utah',             'Nebraska',
         'Pennsylvania',             'Illinois',            'Minnesota',
             'Michigan',             'Delaware',              'Indiana',
             'New York',              'Arizona',             'Virginia',
            'Tennessee',              'Alabama',       'South Carolina',
               'Oregon',             'Colorado',                 'Iowa',
                 'Ohio',             'Missouri',             'Oklahoma',
           'New Mexico',            'Louisiana',          'Connecticut',
           'New Jersey',        'Massachusetts',              'Georgia',
               'Nevada',         'Rhode Island',          'Mississippi',
             'Arkansas',              'Montana',        'New Hampshire',
             'Maryland', 'District of Columbia',               'Kansas',
              'Vermont',                'Maine',         'South Dakota',
                'Idaho',         'North Dakota',              'Wyoming',
        'West Virginia']
Length: 49, dtype: str

Total Unique Countries : 1
Total Unique States    : 49

---

14) Find the count of Every Category
15) Find the count of ship modes

In [25]:
# 14) Count of every Category
print("\nCATEGORY COUNTS:")
print(df['Category'].value_counts())

CATEGORY COUNTS:
Category
Office Supplies    5909
Furniture          2078
Technology         1813
Name: count, dtype: int64

In [26]:
# 15) Count of Ship Modes
print("\nSHIP MODE COUNTS:")
print(df['Ship Mode'].value_counts())

SHIP MODE COUNTS:
Ship Mode
Standard Class    5859
Second Class      1902
First Class       1501
Same Day           538
Name: count, dtype: int64

---

16) Find the total and avg sales Category-wise
17) Find the total and avg sales Segment-wise

In [27]:
# 16) Total and Avg Sales Category-wise
print("CATEGORY-WISE SALES:")
category_sales = df.groupby('Category')['Sales'].agg(
    Total_Sales='sum',
    Avg_Sales='mean'
).round(2)
print(category_sales)

CATEGORY-WISE SALES:
                 Total_Sales  Avg_Sales
Category
Furniture          728658.58     350.65
Office Supplies    705422.33     119.38
Technology         827455.87     456.40

In [31]:
# 17) Total and Avg Sales Segment-wise
print("\nSEGMENT-WISE SALES:")
segment_sales = df.groupby('Segment')['Sales'].agg(
    Total_Sales='sum',
    Avg_Sales='mean'
).round(2)
print(segment_sales)

SEGMENT-WISE SALES:
             Total_Sales  Avg_Sales
Segment
Consumer      1148060.53     225.07
Corporate      688494.07     233.15
Home Office    424982.18     243.40

### Sort

In [32]:
# sort_values()

df.sort_values(by='Sales')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
4101,4102,US-2018-102288,19/06/2018,23/06/2018,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,Texas,77095.0,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444
9292,9293,CA-2018-124114,02/03/2018,02/03/2018,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,Texas,76706.0,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556
8658,8659,CA-2017-168361,21/06/2017,25/06/2017,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,Illinois,60623.0,Central,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836
4711,4712,CA-2015-112403,31/03/2015,31/03/2015,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,OFF-BI-10003529,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852
2106,2107,US-2015-152723,26/09/2015,26/09/2015,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,Texas,75150.0,Central,OFF-BI-10003460,Office Supplies,Binders,Acco 3-Hole Punch,0.876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4190,4191,CA-2018-166709,17/11/2018,22/11/2018,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970
2623,2624,CA-2018-127180,22/10/2018,24/10/2018,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968
8153,8154,CA-2018-140151,23/03/2018,25/03/2018,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,Washington,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960
6826,6827,CA-2017-118689,02/10/2017,09/10/2017,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950
2697,2698,CA-2015-145317,18/03/2015,23/03/2015,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480

In [33]:
df.sort_values(by='Sales', ascending=False)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
2697,2698,CA-2015-145317,18/03/2015,23/03/2015,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480
6826,6827,CA-2017-118689,02/10/2017,09/10/2017,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950
8153,8154,CA-2018-140151,23/03/2018,25/03/2018,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,Washington,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960
2623,2624,CA-2018-127180,22/10/2018,24/10/2018,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968
4190,4191,CA-2018-166709,17/11/2018,22/11/2018,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,2107,US-2015-152723,26/09/2015,26/09/2015,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,Texas,75150.0,Central,OFF-BI-10003460,Office Supplies,Binders,Acco 3-Hole Punch,0.876
4711,4712,CA-2015-112403,31/03/2015,31/03/2015,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,OFF-BI-10003529,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852
8658,8659,CA-2017-168361,21/06/2017,25/06/2017,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,Illinois,60623.0,Central,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836
9292,9293,CA-2018-124114,02/03/2018,02/03/2018,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,Texas,76706.0,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556
4101,4102,US-2018-102288,19/06/2018,23/06/2018,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,Texas,77095.0,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444

---

18) Find ther count of Orders, region-wise
19) Which ship mode is mostly used.
20) Region-wise find the count of different ship modes.

In [34]:
df.groupby("Region")["Order ID"].nunique()

Region
Central    1156
East       1369
South       810
West       1587
Name: Order ID, dtype: int64

In [35]:
df["Ship Mode"].value_counts().idxmax()

'Standard Class'

In [36]:
df.groupby("Region")["Ship Mode"].value_counts()

Region   Ship Mode
Central  Standard Class    1420
         Second Class       447
         First Class        292
         Same Day           118
East     Standard Class    1640
         Second Class       521
         First Class        470
         Same Day           154
South    Standard Class     958
         Second Class       325
         First Class        232
         Same Day            83
West     Standard Class    1841
         Second Class       609
         First Class        507
         Same Day           183
Name: count, dtype: int64

---

22) Find the top 10 Customers(Names) based on total sales.

In [37]:
df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(10)

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

---

23) Find the top 5 cities with the most orders

In [38]:
df.groupby("City")["Order ID"].count().sort_values(ascending=False).head(5)

City
New York City    891
Los Angeles      728
Philadelphia     532
San Francisco    500
Seattle          426
Name: Order ID, dtype: int64

---

24) Which year had the best sales
25) Which Month has the worst sales on avg

In [40]:
print(newDF.groupby("Order Year")["Sales"].sum().idxmax())

2018

---
## Filter data

In [42]:
# Sales > 10000
# df["Sales"]>10000

newDF[newDF["Sales"]>10000]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Order Year,Ship Year
2623,2624,CA-2018-127180,2018-10-22,2018-10-24,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,2018,2018
2697,2698,CA-2015-145317,2015-03-18,2015-03-23,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,2015,2015
4190,4191,CA-2018-166709,2018-11-17,2018-11-22,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,2018,2018
6826,6827,CA-2017-118689,2017-02-10,2017-09-10,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,2017,2017
8153,8154,CA-2018-140151,2018-03-23,2018-03-25,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,Washington,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,2018,2018

In [43]:
# df["Ship Mode"]=="First Class"

newDF[newDF["Ship Mode"]=="First Class"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Order Year,Ship Year
35,36,CA-2017-117590,2017-08-12,2017-10-12,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,2017,2017
36,37,CA-2017-117590,2017-08-12,2017-10-12,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.920,2017,2017
44,45,CA-2017-118255,2017-11-03,2017-03-13,First Class,ON-18715,Odella Nelson,Corporate,United States,Eagan,Minnesota,55122.0,Central,TEC-AC-10000171,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,45.980,2017,2017
45,46,CA-2017-118255,2017-11-03,2017-03-13,First Class,ON-18715,Odella Nelson,Corporate,United States,Eagan,Minnesota,55122.0,Central,OFF-BI-10003291,Office Supplies,Binders,Wilson Jones Leather-Like Binders with DublLoc...,17.460,2017,2017
55,56,CA-2017-111682,2017-06-17,2017-06-18,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,New York,12180.0,East,OFF-ST-10000604,Office Supplies,Storage,Home/Office Personal File Carts,208.560,2017,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9725,9726,CA-2018-142293,2018-09-17,2018-09-20,First Class,SC-20380,Shahid Collister,Consumer,United States,Boise,Idaho,83704.0,West,TEC-AC-10001109,Technology,Accessories,Logitech Trackman Marble Mouse,89.970,2018,2018
9726,9727,CA-2018-167395,2018-02-12,2018-04-12,First Class,KM-16720,Kunst Miller,Consumer,United States,Lowell,Massachusetts,1852.0,East,OFF-AP-10001293,Office Supplies,Appliances,Belkin 8 Outlet Surge Protector,286.860,2018,2018
9727,9728,CA-2018-167395,2018-02-12,2018-04-12,First Class,KM-16720,Kunst Miller,Consumer,United States,Lowell,Massachusetts,1852.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,979.950,2018,2018
9728,9729,CA-2018-167395,2018-02-12,2018-04-12,First Class,KM-16720,Kunst Miller,Consumer,United States,Lowell,Massachusetts,1852.0,East,OFF-SU-10001935,Office Supplies,Supplies,Staple remover,4.360,2018,2018
9752,9753,US-2017-158680,2017-01-07,2017-02-07,First Class,NZ-18565,Nick Zandusky,Home Office,United States,Seattle,Washington,98115.0,West,OFF-BI-10000145,Office Supplies,Binders,Zipper Ring Binder Pockets,2.496,2017,2017

In [45]:
data= data.apply(lambda x : f"{x:.3f}")
data

In [46]:
data=pd.DataFrame({"Marks":[50,60,70,80,90,100]})
data

   Marks
0     50
1     60
2     70
3     80
4     90
5    100

In [47]:
data["Marks"]=data["Marks"].apply(lambda item: item+5)
data

   Marks
0     55
1     65
2     75
3     85
4     95
5    105