### Loc and iLoc

In [ ]:
# loc -- location based indexes or custom indexes
# iloc -- always works upon the basis of integer

In [1]:
import pandas as pd

In [4]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
print(s1.loc[0])

1

In [6]:
print(s1.iloc[0])

1

In [7]:
s2 = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [13]:
print(s2.loc['a'])
# print(s2.loc[0]) -- wont work

1

In [14]:
# print(s2.iloc['a']) -- wont work
print(s2.iloc[0])

1

In [19]:
s3 = pd.Series([1,2,3,4,5], index = [5,6,7,8,9])
s3

5    1
6    2
7    3
8    4
9    5
dtype: int64

In [20]:
print(s3.loc[5])
print(s3.iloc[0])

1
1

### Slicing

In [23]:
s3.iloc[0:2] # last index is always exclusive

5    1
6    2
dtype: int64

In [24]:
s3.loc[5:15] # only with loc the last index is included

5    1
6    2
7    3
8    4
9    5
dtype: int64

In [25]:
s2 = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
s2
# using loc print the values from 1 to 4

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [27]:
s2.loc['a':'d']

a    1
b    2
c    3
d    4
dtype: int64

In [28]:
s2.iloc[0:4]

a    1
b    2
c    3
d    4
dtype: int64

In [29]:
s3 = pd.Series([1,2,3,4,5], index = [5,6,7,8,9])
s3

5    1
6    2
7    3
8    4
9    5
dtype: int64

In [31]:
new = pd.Series([6], index=[0])
s3 = pd.concat([s3, new])
s3

5    6
6    2
7    3
8    4
9    5
0    6
dtype: int64

In [32]:
s0 = pd.Series([1,2,3,4,5])
s0

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [33]:
s0.loc['new_index'] = 10
s0

0             1
1             2
2             3
3             4
4             5
new_index    10
dtype: int64

In [34]:
s0['cool'] = 67
s0

0             1
1             2
2             3
3             4
4             5
new_index    10
cool         67
dtype: int64

# Data Frames
### Creating a dataframe

In [35]:
# We create a DF using nested lists and dictionaries

In [36]:
data = {"Name":['a','c','b'],
        "Age":[21,34,46]}

df = pd.DataFrame(data)
df

  Name  Age
0    a   21
1    c   34
2    b   46

In [38]:
data = {"Name":['month','sales','profit'],
        "Value":['Jan',67,6999]}

df = pd.DataFrame(data)
df

     Name Value
0   month   Jan
1   sales    67
2  profit  6999

In [40]:
# create a dict which is having the months, sales, profit
# convert the dict into DataFrame

sales_data= {
"Month": ["January", "February", "March", "April", "May"],
"Sales": [50000, 62000, 58000, 70000, 75000],
"Profit": [12000, 15000, 14000, 18000, 20000]
}

df = pd.DataFrame(sales_data)

In [41]:
df

      Month  Sales  Profit
0   January  50000   12000
1  February  62000   15000
2     March  58000   14000
3     April  70000   18000
4       May  75000   20000

In [42]:
data = [['R6', 670], ['RE9', 2400]]
df = pd.DataFrame(data, columns = ['Game', 'Price'])
df

  Game  Price
0   R6    670
1  RE9   2400

In [46]:
df['Dev'] = ['UbiSoft', 'Tencent']
df

  Game  Price     2      Dev
0   R6    670  PUBG  UbiSoft
1  RE9   2400   500  Tencent

In [50]:
data = { "name": [ "DeLorean DMC-12", "Batmobile (1989)", "Ecto-1", "Eleanor (Mustang GT500)", "KITT (Trans Am)", "Mad Max Interceptor", "Mach 5", "Banshee (GTA V)", "Rocket (Cyberpunk 2077)", "Lightning McQueen", "Infernus (GTA SA)", "F-Zero Blue Falcon", "Warthog (Halo)" ], 
         "source": [ "Back to the Future", "Batman (1989)", "Ghostbusters", "Gone in 60 Seconds", "Knight Rider", "Mad Max 2", "Speed Racer", "GTA V", "Cyberpunk 2077", "Cars (Pixar)", "GTA San Andreas", "F-Zero", "Halo Series" ], 
         "type": [ "Movie", "Movie", "Movie", "Movie", "Movie", "Movie", "Movie", "Game", "Game", "Movie", "Game", "Game", "Game" ], 
         "year": [ 1981, 1989, 1959, 1967, 1982, 1973, 1967, 2013, 2077, 2006, 2004, 1990, 2001 ], 
         "price_usd": [ 25_000, 4_200_000, 4_500, 1_000_000, 3_900_000, 500_000, 15_000_000, 180_000, 620_000, 400_000, 85_000, 8_000_000, 320_000 ] 
       } 
df = pd.DataFrame(data) 
df

                       name              source   type  year  price_usd
0           DeLorean DMC-12  Back to the Future  Movie  1981      25000
1          Batmobile (1989)       Batman (1989)  Movie  1989    4200000
2                    Ecto-1        Ghostbusters  Movie  1959       4500
3   Eleanor (Mustang GT500)  Gone in 60 Seconds  Movie  1967    1000000
4           KITT (Trans Am)        Knight Rider  Movie  1982    3900000
5       Mad Max Interceptor           Mad Max 2  Movie  1973     500000
6                    Mach 5         Speed Racer  Movie  1967   15000000
7           Banshee (GTA V)               GTA V   Game  2013     180000
8   Rocket (Cyberpunk 2077)      Cyberpunk 2077   Game  2077     620000
9         Lightning McQueen        Cars (Pixar)  Movie  2006     400000
10        Infernus (GTA SA)     GTA San Andreas   Game  2004      85000
11       F-Zero Blue Falcon              F-Zero   Game  1990    8000000
12           Warthog (Halo)         Halo Series   Game  2001     320000

In [51]:
data = {
    'Cars':["Skyline GTR","mustang","Lamborghini","nexon","Ford Figo","Toyota Camry", "Honda City"],
    "Price": ["4000000","50000000","60000000",'56450000',"638438",'793874','792874937'],
    "model": [2023,2021,2019,2025, 2020,2022,2024]
}

In [52]:
cars_df = pd.DataFrame(data)

In [53]:
cars_df

           Cars      Price  model
0   Skyline GTR    4000000   2023
1       mustang   50000000   2021
2   Lamborghini   60000000   2019
3         nexon   56450000   2025
4     Ford Figo     638438   2020
5  Toyota Camry     793874   2022
6    Honda City  792874937   2024

In [54]:
cars_df.loc[1]

Cars      mustang
Price    50000000
model        2021
Name: 1, dtype: object

In [55]:
cars_df.iloc[5]

Cars     Toyota Camry
Price          793874
model            2022
Name: 5, dtype: object

In [57]:
# print column
cars_df['Cars']

0     Skyline GTR
1         mustang
2     Lamborghini
3           nexon
4       Ford Figo
5    Toyota Camry
6      Honda City
Name: Cars, dtype: str

In [59]:
#  print multiple columns
cars_df[['Cars', 'model']]

           Cars  model
0   Skyline GTR   2023
1       mustang   2021
2   Lamborghini   2019
3         nexon   2025
4     Ford Figo   2020
5  Toyota Camry   2022
6    Honda City   2024

In [60]:
cars_df['Cars'].loc[1]

'mustang'

In [61]:
cars_df.loc[0]['Cars']

'Skyline GTR'

In [67]:
cars_df.iloc[4:7][['Cars', 'Price']]

           Cars      Price
4     Ford Figo     638438
5  Toyota Camry     793874
6    Honda City  792874937

In [69]:
cars_df.loc[4:7, 'Cars':'Price']

           Cars      Price
4     Ford Figo     638438
5  Toyota Camry     793874
6    Honda City  792874937

In [71]:
cars_df.loc[4:7, ['Cars', 'Price']]

           Cars      Price
4     Ford Figo     638438
5  Toyota Camry     793874
6    Honda City  792874937

In [72]:
# Replace

# replace any data

cars_df['Cars'] = cars_df['Cars'].replace('mustang', 'Mustang')
cars_df

           Cars      Price  model
0   Skyline GTR    4000000   2023
1       Mustang   50000000   2021
2   Lamborghini   60000000   2019
3         nexon   56450000   2025
4     Ford Figo     638438   2020
5  Toyota Camry     793874   2022
6    Honda City  792874937   2024

In [73]:
cars_df = cars_df.rename(columns = {"model":"Year"})
cars_df

           Cars      Price  Year
0   Skyline GTR    4000000  2023
1       Mustang   50000000  2021
2   Lamborghini   60000000  2019
3         nexon   56450000  2025
4     Ford Figo     638438  2020
5  Toyota Camry     793874  2022
6    Honda City  792874937  2024

In [74]:
# check datatype

cars_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Cars    7 non-null      str
 1   Price   7 non-null      str
 2   Year    7 non-null      int64
dtypes: int64(1), str(2)
memory usage: 300.0 bytes

In [75]:
cars_df['Price'] = cars_df['Price'].astype(int)

In [76]:
cars_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Cars    7 non-null      str
 1   Price   7 non-null      int64
 2   Year    7 non-null      int64
dtypes: int64(2), str(1)
memory usage: 300.0 bytes

In [77]:
new_rows = pd.DataFrame({
    "Cars": ['Tata',"Hyundai","Mercedes"],
    "Price":[97349,789438,8900000],
    "Year":[2020,2025,2024]
})

new_rows

       Cars    Price  Year
0      Tata    97349  2020
1   Hyundai   789438  2025
2  Mercedes  8900000  2024

In [78]:
cars_df = pd.concat([cars_df,new_rows], ignore_index=True)
cars_df

           Cars      Price  Year
0   Skyline GTR    4000000  2023
1       Mustang   50000000  2021
2   Lamborghini   60000000  2019
3         nexon   56450000  2025
4     Ford Figo     638438  2020
5  Toyota Camry     793874  2022
6    Honda City  792874937  2024
7          Tata      97349  2020
8       Hyundai     789438  2025
9      Mercedes    8900000  2024

## Loading the dataset file

In [86]:
# Option 1 — relative path (recommended, works from within the Pandas folder)
df = pd.read_csv("Dataset/mtcars2.csv")

# Option 2 — full absolute path
# df = pd.read_csv(r"C:\path\to\Python\Pandas\Dataset\mtcars2.csv")

# Verify it loaded correctly
print(df.head())
print(df.shape)

   S.No         Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0     1          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1
1     2      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1
2     3         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1
3     4     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0
4     5  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0

   gear  carb
0     4     4
1     4     4
2     4     1
3     3     1
4     3     2
(32, 13)

In [81]:
df.shape

(32, 13)

In [82]:
df

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [88]:
df.columns

Index(['S.No', 'Unnamed: 1', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec',
       'vs', 'am', 'gear', 'carb'],
      dtype='str')

In [89]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   S.No        32 non-null     int64
 1   Unnamed: 1  32 non-null     str
 2   mpg         32 non-null     float64
 3   cyl         32 non-null     int64
 4   disp        32 non-null     float64
 5   hp          32 non-null     int64
 6   drat        32 non-null     float64
 7   wt          32 non-null     float64
 8   qsec        29 non-null     float64
 9   vs          32 non-null     int64
 10  am          32 non-null     int64
 11  gear        32 non-null     int64
 12  carb        32 non-null     int64
dtypes: float64(5), int64(7), str(1)
memory usage: 3.4 KB

In [ ]:
# duplicate